<table class="table table-hover">
    <thead>
    <tr>
        <th>pict</th>
        <th>name</th>
        <th>desc</th>
        <th>price</th>
    </tr>

    </thead>
    <tbody>
<?php foreach ($this->works as $work) :?>
    <tr>
        <th><img src="<?php echo $this->imagePath . '/' . $work->getPictureHash();?>" width="150" height="150"></th>
        <th><?php echo $work->getName();?></th>
        <th><?php echo $work->getDescription();?></th>
        <th><?php echo $work->getPrice();?></th>
    </tr>
<?php endforeach;?>
    </tbody>
</table>