<!--<ul class="nav nav-tabs" id="myTab">
    <li class="active"><a href="#home">Home</a></li>
    <li><a href="#profile">Profile</a></li>
    <li><a href="#messages">Messages</a></li>
    <li><a href="#settings">Settings</a></li>
</ul>
<div class="tab-content">
    <div class="tab-pane active" id="home">

    </div>
    <div class="tab-pane" id="profile">
        Profile
    </div>
    <div class="tab-pane" id="messages">
        Messages
    </div>
    <div class="tab-pane" id="settings">
        Settings
    </div>
</div>

<!--<a href="--><?php /*//echo $this->url('album', array('action'=>'add'));*/?><!--" class="btn btn-primary">Add new album</a>-->
<!--<a href="--><?php //echo $this->url('zfcuser/register'); ?><!--">Registration</a><br>-->
<!--<a href="--><?php //echo $this->url('zfcuser/login'); ?><!--">Sign In</a>-->
Home Page

<script>
    $('#myTab a').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    })
</script>