<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php if ($this->isAllowed('controller/Album\Controller\Album:add')) :?>
                        <li><a href="<?php echo $this->url('album', array('action'=>'add')) ?>"><?php echo $this->translate('Add Album') ?></a></li>
                        <?php else: ?>
                        <li><a href="<?php echo $this->url('zfcuser/register'); ?>"><?php echo $this->translate('Registration') ?></a></li>
                        <li><a href="<?php echo $this->url('zfcuser/login'); ?>"><?php echo $this->translate('Sign In') ?></a></li>
                        <?php endif; ?>
                        <?php if ($this->isAllowed('controller/zfcuser:logout')) :?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <?php echo $this->translate('My Account') ?>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('Go to account'); ?></a></li>
                                    <?php if ($this->isAllowed('controller/work:add')) :?>
                                        <li><a href="<?php echo $this->url('work/show') ?>"><?php echo $this->translate('Show works'); ?></a></li>
                                        <li><a href="<?php echo $this->url('work/add') ?>"><?php echo $this->translate('Add work'); ?></a></li>
                                    <?php endif;?>
                                    <li><a href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo $this->translate('Sign Out'); ?></a></li>
                                </ul>
                            </li>
                        <?php endif; ?>
                        <li><a href="<?php echo $this->url('work/search'); ?>"><?php echo $this->translate('Search') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>Yauhen Siniauski &#169; 2013</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
